stages:
  - build

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    #- target/

build-window:
  image: adoptopenjdk:11-hotspot
  stage: build
  script:
    - sh mvnw $MAVEN_CLI_OPTS -f pom-win.xml package
  artifacts:
    paths:
      - target/game-fatJar.jar
      - target/res/*
      
build-linux:
  image: adoptopenjdk:11-hotspot
  stage: build
  script:
    - sh mvnw $MAVEN_CLI_OPTS package
  artifacts:
    paths:
      - target/game-fatJar.jar
      - target/res/*
      - target/LilithsThrone*
