on:
  push:
    branches: [ graaljs&jfx-fatjar ]
  pull_request:
    branches: [ graaljs&jfx-fatjar ]

jobs:
  build:

    runs-on: [ ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
